version: "3.8"

services:
  frontend:
    container_name: react-starter-app
    image: react-starter-app
    build:
      context: .
      dockerfile: Dockerfiledev
      target: development
    volumes:
      - ./src:/app/src
      # Exclude node_modules, so iterating on the backend doesn't require installing frontend dependencies locally
      - /app/node_modules
    ports:
      - 3001:3001